config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root "main#index"
get "/signup", to: "users#new", as: "new_user"
post '/users', to: 'users#create'
get '/profile', to: 'users#show', as: 'user'
get "/users/:id/edit", to: 'users#edit', as: 'edit_user'
put '/users/:id', to: 'users#update', as: 'update_user'
delete '/users/:id', to: 'users#destroy', as:"delete_user"

get '/login', to: 'sessions#new'
post '/sessions', to: 'sessions#create'
get '/logout', to: 'sessions#destroy'

get '/recipes', to: 'recipes#index', as: "recipes"
post "/recipes", to: 'recipes#index'
post '/recipesave', to: 'recipes#create', as:'recipesave'
delete '/recipes/:id', to: 'recipes#destroy', as:"delete_recipe"

get '/restaurants', to: 'restaurants#index', as: "restaurants"
post "/restaurants", to: 'restaurants#index'
post '/restaurantssave', to: 'restaurants#create', as:'restaurantssave'
delete '/restaurants/:id', to: 'restaurants#destroy', as:"delete_restaurant"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  	belongs_to :user
	include HTTParty
	base_uri 'http://food2fork.com/api'
	default_params key: ENV["FOOD2FORK_KEY"]
 	format :json
 
 def self.for(term)
	get("/search", query: { q: term})["recipes"]
 end
 def self.ing(id)
 	get('/get', query: {rId: id})["recipe"]
 end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
	API_HOST = "https://api.yelp.com"
	SEARCH_PATH = "/v3/businesses/search"
	BUSINESS_PATH = "/v3/businesses/"  # trailing / because we append the business id to the path
	TOKEN_PATH = "/oauth2/token"
	GRANT_TYPE = "client_credentials"

  def self.search(term, location)
  auth = "Bearer " + ENV['YELP_API']

  url = "#{API_HOST}#{SEARCH_PATH}"
  params = {
    term: term,
    location: location,
  }
  response = HTTP.auth(auth).get(url, params: params)
  response.parse
  end


end

app/models/user.rb
class User < ApplicationRecord
	validates :password, presence: true, length: {minimum: 6}
	validates :username, presence: true, uniqueness: true
	has_many :recipes, dependent: :destroy
	has_many :restaurants, dependent: :destroy
	has_secure_password
	def self.confirm(params)
  	@user = User.find_by({username: params[:username]})
  	@user ? @user.authenticate(params[:password]) : false
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	def index
		
	end 
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	
	def index
		@search_term = params[:looking_for]
  		@recipes = Recipe.for(@search_term)
  		@randomrecipes = @recipes.sample(3)
  		@randomrecipes.each do |course|
	  		search_ing = course["recipe_id"]
  			@ingredients = Recipe.ing(search_ing)
  		end 
	end 
	def create
		user = current_user
		@recipe = user.recipes.new(name: params[:name], 
			date: DateTime.now, 
			ingredient: params[:ingredient], 
			image: params[:image])
		if @recipe.save
			ReminderMailer.reminder_emailrecipe(user).deliver_later
			flash[:success] = "You saved this recipe"
			redirect_to recipes_path
		else
			flash[:error] = @recipe.errors.full_messages.join(' ')
			redirect_to recipes_path
		end
	end 
	def destroy
		user = current_user
		recipes = user.recipes
		recipe = recipes.find(params[:id])
		recipe.destroy
		redirect_to user_path(user) 
	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@term = params[:term]
		@location = params[:location]
		@restaurant = Restaurant.search(@term, @location)
		if @restaurant["businesses"] == nil
			@location = "SF"
			@restaurant = Restaurant.search(@term, @location)
			@restaurant = @restaurant["businesses"].sample(3)

		else
			@restaurant = @restaurant["businesses"].sample(3)
		end 
		
	end 
	def create
		user = current_user
		@restaurant = user.restaurants.new(name: params[:name], 
		address: params[:address], 
		price: params[:price],
		category: params[:category],
		link: params[:link],
		image: params[:image])
		if @restaurant.save
			ReminderMailer.reminder_email(user).deliver_later
			flash[:success] = "You saved this restaurant"
			redirect_to restaurants_path
		else
			flash[:error] = @restaurant.errors.full_messages.join(' ')
			redirect_to restaurants_path
		end
	end 
	def destroy
		user = current_user
		restaurants = user.restaurants
		restaurant = restaurants.find(params[:id])
		restaurant.destroy
		redirect_to user_path(user) 
	end

end

app/controllers/sessions_controller.rb
 class SessionsController < ApplicationController
	def new
		@user = User.new
	end
	def create
		@user = User.confirm(user_params)
		if @user
			login(@user)
			flash[:notice] = "Successfully logged in."
			redirect_to user_path(@user)
		else
			flash[:error] = "Incorrect email or password."
      redirect_to login_path
   	end
	end
	def destroy
    logout
    redirect_to root_path
  end
	private
	def user_params
		params.require(:user).permit(:username, :password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end 
	def new 
		@user = User.new
	end 
	def create 
		@user = User.new(user_params)
		if @user.save
			login(@user)
			redirect_to user_path(@user)
		else
			flash[:error] = @user.errors.full_messages.join(' ')
			redirect_to new_user_path
		end 
	end 
	def show
		@user = User.find(session[:user_id])
		@recipes = @user.recipes
		@restaurants = @user.restaurants
	end 
	private
	def user_params
		params.require(:user).permit(:first_name, :last_name, :email, :username, :password)
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login(user)
		session[:user_id] = user.id
		@current_user = user
	end
	def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  def logout
    @current_user = session[:user_id] = nil
    flash[:notice] = "Successfully logged out."
  end
	#TODO: doublecheck this require_login method.
  def require_login
    if @current_user != nil
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>REat</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  </head>

  <body>
    <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <div class="navbar-brand">R-EAT</div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
             <% if current_user %>
                <li class="nav-link"><%= link_to "Profile", user_path(current_user) %></li>
                <li class="nav-link"><%= link_to "Recipe", recipes_path%></li>
                <li class="nav-link"><%= link_to "Restaurant", restaurants_path%></li>
                <li class="nav-link"><%= link_to "Log Out", logout_path %></li>
              <% else %>
                <li class="nav-link"><%= link_to "Sign Up ", new_user_path %></li>
                <li class="nav-link"><%= link_to "Log In", login_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

    <% flash.each do |name, msg| %>
    <div id="flash-message" class="<%= name %>">
      <div class="container">
        <p>
          <%= name.capitalize %>: <%= msg %>
        </p>
      </div>
    </div>
    <% end %>
    <%= yield %>

  
  </body>
</html>

app/views/main/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>One Page Wonder - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->


    <!-- Custom styles for this template -->

  </head>

  <body>

    <header class="masthead">
      <div class="overlay">
        <div class="container">
          <h1 class="display-1 text-white">Wonderful Foods</h1>
          <h2 class="display-4 text-white">Unexpected Food Journeys</h2>
        </div>
      </div>
    </header>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-2">
            <div class="p-5">
              <img src="<%= asset_path("2.jpg")%>" class="img-fluid rounded-circle">
            </div>
          </div>
          <div class="col-md-6 order-1">
            <div class="p-5">
              <h2 class="display-4">For those about to eat...</h2>
              <p>“Pull up a chair. Take a taste. Come join us. Life is so endlessly delicious.” 
                ― Ruth Reichl.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6">
            <div class="p-5">
              <img src="<%= asset_path("1.jpg")%>" class="img-fluid rounded-circle">
            </div>
          </div>
          <div class="col-md-6">
            <div class="p-5">
              <h2 class="display-4">We salute you!</h2>
              <p>“Let food be thy medicine and medicine be thy food.” 
                ― Hippocrates</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-2">
            <div class="p-5">
              <img src="<%= asset_path("3.jpg")%>" class="img-fluid rounded-circle">
            </div>
          </div>
          <div class="col-md-6 order-1">
            <div class="p-5">
              <h2 class="display-4">Let there be Food!</h2>
              <p>“This above all: to thine own self be true, 
                  And it must follow, as the night the day, 
                  Thou canst not then be false to any man.” 
                  ― William Shakespeare, Hamlet</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; R-Eat 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
 
  </body>

</html>

app/views/recipes/_form.html.erb
<%= form_tag recipes_path do %>
  <label for="lookup">Lookup</label>
  <%= text_field_tag :looking_for %>
  <%= submit_tag "Submit" %>
<% end %>

app/views/recipes/index.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">


  </head>

  <body>
  	<% if (@search_term.nil?) %>
  	<header class="masthead">
      <div class="overlay">
        <div class="container">
          <h1 class="display-1 text-white">Wonderful Foods</h1>
          <h2 class="display-4 text-white">Unexpected Food Journeys</h2>
        </div>
      </div>
    </header>
      <br>
  		<div class="text-center"><%= render "form"%></div>
  		    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-2">
            <div class="p-5">
              <img src="<%= asset_path("2.jpg")%>" class="img-fluid rounded-circle">
            </div>
          </div>
          <div class="col-md-6 order-1">
            <div class="p-5">
              <h2 class="display-4">For those about to eat...</h2>
              <p>“Pull up a chair. Take a taste. Come join us. Life is so endlessly delicious.” 
				― Ruth Reichl</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6">
            <div class="p-5">
              <img src="<%= asset_path("1.jpg")%>" class="img-fluid rounded-circle">
            </div>
          </div>
          <div class="col-md-6">
            <div class="p-5">
              <h2 class="display-4">We salute you!</h2>
              <p>“Let food be thy medicine and medicine be thy food.” 
				― Hippocrates</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-2">
            <div class="p-5">
              <img src="<%= asset_path("3.jpg")%>" class="img-fluid rounded-circle">
            </div>
          </div>
          <div class="col-md-6 order-1">
            <div class="p-5">
              <h2 class="display-4">Let there be Food!</h2>
              <p>“This above all: to thine own self be true, 
					And it must follow, as the night the day, 
					Thou canst not then be false to any man.” 
					― William Shakespeare, Hamlet</p>
            </div>
          </div>
        </div>
      </div>
    </section>


  		
	<% else %>
  	
    <header class="masthead">
      <div class="overlay">
        <div class="container">
          <h1 class="display-1 text-white">One Page Wonder</h1>
          <h2 class="display-4 text-white">Unexpected Food Journeys</h2>
        </div>
      </div>
    </header>
      <br>
  <div class="text-center"><%= render "form"%></div>
    <h1>Searching for - <%= @search_term %></h1>
	  <% @randomrecipes.each do |course| %>

	    <section>
	      <div class="container">
	        <div class="row align-items-center">
	          <div class="col-md-6 order-2">
	            <div class="p-5">
	             <%= link_to(image_tag(course["image_url"], height: '300', width: '300',class: "img-fluid rounded-circle"), course["f2f_url"])%>
	            </div>
	          </div>
	          <div class="col-md-6 order-1">
	            <div class="p-5">
	              <h2 class="display-4"><%= link_to(course["title"], course["f2f_url"]) %></h2>
					<h5><%= "Rating #{course["social_rank"].to_i}/100" %></h5>
					<h4>Ingredients</h4>
					<h5><% @ingredients["ingredients"].each do |ingredient| %></h5>
					<h5><%= ingredient%></h5>
					<% end%>
					
					<%= form_with url: recipesave_path do|f|%>
	 
	          			<%= f.hidden_field :name, value: course["title"]%>
	          			<%= f.hidden_field :image, value: course["image_url"]%>

	          			<%= f.hidden_field :ingredient, value: @ingredients["ingredients"]%>
	      				<%= f.submit "Save"%>
	    			<% end %>

	    	 	
	            </div>
	          </div>
	        </div>
	      </div>
	    </section>
	   <% end %>
    <% end %>
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; R-Eat 2017</p>
    <p class="m-0 text-center text-white">Powered By Food2Fork.com</p>
  </div>
  <!-- /.container -->
</footer>
</body>

</html>

app/views/restaurants/_form.html.erb
<%= form_tag restaurants_path do  %>
  <label for="lookup">Lookup</label>
  <%= text_field_tag :term %>
  <%= text_field_tag :location%>
  <%= submit_tag "Submit" %>
<% end %>

app/views/restaurants/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

  </head>

  <body>
    <% if (@term.nil? || @location.nil?) %>
    <header class="masthead">
      <div class="overlay">
        <div class="container">
          <h1 class="display-1 text-white">Wonderful Foods</h1>
          <h2 class="display-4 text-white">Unexpected Food Journeys</h2>
        </div>
      </div>
    </header>
      <br>
      <div class="text-center"><%= render "form"%></div>
          <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-2">
            <div class="p-5">
              <img src="<%= asset_path("3.jpg")%>" class="img-fluid rounded-circle">
            </div>
          </div>
          <div class="col-md-6 order-1">
            <div class="p-5">
              <h2 class="display-4">For those about to eat...</h2>
              <p>“Pull up a chair. Take a taste. Come join us. Life is so endlessly delicious.” 
              ― Ruth Reichl</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6">
            <div class="p-5">
              <img src="<%= asset_path("2.jpg")%>" class="img-fluid rounded-circle">
            </div>
          </div>
          <div class="col-md-6">
            <div class="p-5">
              <h2 class="display-4">We salute you!</h2>
              <p>“Let food be thy medicine and medicine be thy food.” 
                ― Hippocrates</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-2">
            <div class="p-5">
              <img src="<%= asset_path("1.jpg")%>" class="img-fluid rounded-circle">
            </div>
          </div>
          <div class="col-md-6 order-1">
            <div class="p-5">
              <h2 class="display-4">Let there be Food!</h2>
              <p>“This above all: to thine own self be true, 
                  And it must follow, as the night the day, 
                  Thou canst not then be false to any man.” 
                  ― William Shakespeare, Hamlet</p>
            </div>
          </div>
        </div>
      </div>
    </section>


      
  <% else %>
    <header class="masthead">
      <div class="overlay">
        <div class="container">
          <h1 class="display-1 text-white">One Page Wonder</h1>
          <h2 class="display-4 text-white">Unexpected Food Journeys</h2>
        </div>
      </div>
    </header>
    <br>
    <div class="text-center"><%= render "form"%></div>
    <% @restaurant.each do |business|%>
	
    <section>
      <div class="container">
        <div class="row align-items-center">
          <div class="col-md-6 order-2">
            <div class="p-5">
             <%= image_tag(business["image_url"], height: '300', width: '300',class: "img-fluid rounded-circle")%>
            </div>
          </div>
          <div class="col-md-6 order-1">
            <div class="p-5">
              <h2 class="display-4"><%= link_to business["name"], business["url"]%></h2>
              	<% business["categories"].each do |category|%>
					<h4><%= category["title"]%></h4>
				<% end %>
				<h5><%= "Rating #{business["rating"]}/5"%></h5>
				<% business["location"]["display_address"].each do |address|%>
          <%= address%>
        <% end%>
				<h5><%= business["display_phone"]%></h5>
				<h5><%= business["price"]%></h5> 
				<%= form_with url: restaurantssave_path do|f|%>
				  <%= f.hidden_field :link, value: business["url"]%>
          <%= f.hidden_field :image, value: business["image_url"]%>
		 		  <%= f.hidden_field :name, value: business["name"]%>
		 		  <%= f.hidden_field :address, value:  business["location"]["display_address"]%>
		 		  <%= f.hidden_field :price, value: business["price"]%>
		          <% business["categories"].each do |category|%>
				  	<%= f.hidden_field :category, value: category["title"]%>
				  <% end %>
		      	  <%= f.submit "Save"%>
		      	<% end %>      	 	
            </div>
          </div>
        </div>
      </div>
    </section>
    <% end %>
    <% end %>



    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; R-Eat 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
 
  </body>

</html>

app/views/users/new.html.erb
<section class="container" id="login">
  <h1>Sign Up!</h1>
  <div class="row">
    <%= form_with class: "col s12",scope: :user, url: "/users" do|f|%>
      <div class="row">
        <div class="input-field col s6">
          <%= f.text_field :first_name,id: "first_name",class: "validate", placeholder: "First Name", required: true%>
          <%= f.label :first_name %>
        </div>
        <div class="input-field col s6">
          <%= f.text_field :last_name,id: "last_name",class: "validate", placeholder: "Last Name", required: true %>
          <%= f.label :last_name %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :username,id: "username",class: "validate", placeholder: "Username", required: true %>
          <%= f.label :username %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.text_field :email,id: "email",class: "validate", placeholder: "Email", required: true %>
          <%= f.label :email %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s12">
          <%= f.password_field :password,id: "pass",class: "validate", placeholder: "Password", required: true %>
          <%= f.label :password %>
        </div>
      </div>
      <%= f.submit "Sign Up", class: "btn waves-effect waves-light btn-large" %>
    <% end %>

  </div>
</section>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta content="IE=edge" http-equiv="X-UA-Compatible">
  <meta content="width=device-width,initial-scale=1" name="viewport">
  <meta content="Page description" name="description">
  <meta name="google" content="notranslate" />
  <meta content="Mashup templates have been developped by Orson.io team" name="author">

  <!-- Disable tap highlight on IE -->
  <meta name="msapplication-tap-highlight" content="no">

<body>

<main class="" id="main-collapse">

<div class="hero-full-wrapper">
  <div class="grid">
  <div class="gutter-sizer"></div>
    <div class="grid-sizer"></div>
 <% @recipes.each do |recipe|%>  
    <div class="grid-item">
   	  <%= image_tag(recipe.image, height: '300', width: '300',class: "img-responsive img-fluid rounded-circle")%>
        <div class="project-text-holder">
          <div class="project-text-inner">
          	<h3><%= recipe.date.to_date%></h3>
            <h3><%= recipe.name%></h3>
            <p><% ingredient = recipe.ingredient%></p>
	 		<p><% ingredient.each do |ing|%></p>
	 			<%= ing %>
	 		<% end %>
      <br>
         <%=link_to "Delete", delete_recipe_path(recipe.id), method: :delete, class: "btn btn-danger btn-sm"%>
          </div>
        </div>
    </div>
  <% end %>

 <% @restaurants.each do |restaurant|%>
    <div class="grid-item">
 	  <%= image_tag(restaurant.image, height: '300', width: '300',class: "img-responsive img-fluid rounded-circle")%> 
        <div class="project-text-holder">
          <div class="project-text-inner">
          	<h3><%= restaurant.created_at.to_date%></h3>
            <h3><%=link_to restaurant.name, restaurant.link%></h3>
	 		<p><%= restaurant.address%></p>
	 		<p><%= restaurant.price%></p>
	 		<p><%= restaurant.category%></p>
          <%=link_to "Delete", delete_restaurant_path(restaurant.id), method: :delete, class: "btn btn-danger btn-sm"%> 
          </div>
        </div>
    </div>
  <% end %>

</div>
</div>

 <script>
  document.addEventListener("DOMContentLoaded", function (event) {
     masonryBuild();
  });
</script>
</main>
<script>
document.addEventListener("DOMContentLoaded", function (event) {
  navbarToggleSidebar();
  navActivePage();
});
</script>
</body>
</html>